# Generated by Django 3.2.19 on 2023-06-28 09:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_user_event_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interested', '0002_alter_interested_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interested',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='interested',
            unique_together={('owner', 'event')},
        ),
    ]
