# Generated by Django 3.2.19 on 2023-06-07 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('country', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='../equal-rights_o1owqr', upload_to='images/')),
                ('image_filter', models.CharField(choices=[('_1977', '1977'), ('brannan', 'Brannan'), ('earlybird', 'Earlybird'), ('hudson', 'Hudson'), ('inkwell', 'Inkwell'), ('lofi', 'Lo-Fi'), ('kelvin', 'Kelvin'), ('normal', 'Normal'), ('nashville', 'Nashville'), ('rise', 'Rise'), ('toaster', 'Toaster'), ('valencia', 'Valencia'), ('walden', 'Walden'), ('xpro2', 'X-pro II')], default='Normal', max_length=32)),
                ('event_date', models.DateField()),
                ('category', models.CharField(choices=[('Discrimination', 'Descrimination'), ('LQBTQ', 'LGBTQ'), ('Equal-Rights', 'Equal Rights'), ('Marraige', 'Marraige'), ('Work', 'Work'), ('Education', 'Education')], default='Equal-Rights', max_length=50)),
                ('sub_category', models.CharField(choices=[('Seminars', 'Seminars'), ('Webinars', 'Webinars'), ('Retreats', 'Retreats')], default='Seminars', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
