# Generated by Django 3.2.19 on 2023-06-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20230609_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sub_category',
            field=models.CharField(choices=[('Seminars', 'Seminars'), ('Meet-ups', 'Meet-ups'), ('Retreats', 'Retreats')], default='Seminars', max_length=50),
        ),
    ]
