# Generated by Django 3.2.19 on 2023-06-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='country',
        ),
    ]
