# Generated by Django 3.2.19 on 2023-06-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='owner',
        ),
    ]
