# Generated by Django 3.2.19 on 2023-06-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_user_event_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Discrimination', 'Descrimination'), ('LGBTQ', 'LGBTQ'), ('Equal-Rights', 'Equal Rights'), ('Marraige-Rights', 'Marraige Rights'), ('Work-Rights', 'Work Rights'), ('Education-Rights', 'Education Rights')], default='Equal-Rights', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_filter',
            field=models.CharField(choices=[('_1977', '1977'), ('brannan', 'Brannan'), ('earlybird', 'Earlybird'), ('hudson', 'Hudson'), ('inkwell', 'Inkwell'), ('lofi', 'Lo-Fi'), ('kelvin', 'Kelvin'), ('normal', 'Normal'), ('nashville', 'Nashville'), ('rise', 'Rise'), ('toaster', 'Toaster'), ('valencia', 'Valencia'), ('walden', 'Walden'), ('xpro2', 'X-pro II')], default='normal', max_length=32),
        ),
    ]
