# Generated by Django 3.2.19 on 2023-06-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='profile',
        ),
    ]
