# Generated by Django 3.2.19 on 2023-06-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_remove_join_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='join',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
