# Generated by Django 3.2.19 on 2023-06-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0004_auto_20230614_0856'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='join',
            unique_together=set(),
        ),
    ]
