# Generated by Django 3.2.19 on 2023-06-14 09:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_alter_event_category'),
        ('join', '0005_alter_join_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='join',
            unique_together={('user', 'event')},
        ),
    ]
