# Generated by Django 3.2.19 on 2023-06-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0008_auto_20230614_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='email',
        ),
        migrations.RemoveField(
            model_name='join',
            name='name',
        ),
    ]
