# Generated by Django 3.2.19 on 2023-06-28 09:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_rename_user_event_owner'),
        ('join', '0009_auto_20230624_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='join',
            unique_together={('owner', 'event')},
        ),
    ]
